esphome:
  name: 
  friendly_name: 

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ""
    password: ""

captive_portal:
# our code
#declaration of sensor
sensor:
  - platform: adc 
    pin: 0 # pin for sensor
    name: "ESP32-C3-gas-sensor" #name of entity in HA
    update_interval: 1s 
    filters:
      - multiply: 100 #multiply the adc value to get %
    unit_of_measurement: "%"
    icon: "mdi:percent"
#declaration for tamper
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO4                 
      mode: INPUT_PULLUP
      inverted: true
    id: tamper_sensor
    name: "Tamper Switch"
    device_class: tamper
    on_press: # manipulation detected                      
      - switch.turn_on: tamper_output
      - logger.log: "TAMPER DETECTED → GPIO7 HIGH" #alarm message
    on_release:                     
      - switch.turn_off: tamper_output
      - logger.log: "Tamper closed → GPIO7 LOW" 

switch:
  - platform: gpio
    pin: GPIO7
    id: tamper_output
    internal: true
    
      


    
